### ISSUE TITLE
Selenium server is not shutting down correctly

### ISSUE THREAD

**Issue by dominik0711** [Polymer/web-component-tester#110]
We use automatic wct testing in combination with Codeship CI service. Often we receive the following error: 
```
15:59:36.166 WARN - Failed to start: SocketListener0@0.0.0.0:51327
Exception in thread "main"
java.net.BindException: Selenium is already running on port 51327. Or some other service is.
    at org.openqa.selenium.server.SeleniumServer.start(SeleniumServer.java:491)
    at org.openqa.selenium.server.SeleniumServer.boot(SeleniumServer.java:300)
    at org.openqa.selenium.server.SeleniumServer.main(SeleniumServer.java:245)
    at org.openqa.grid.selenium.GridLauncher.main(GridLauncher.java:97)
Could not start Selenium
```

1: Is it possible to use dynamic ports for every test suite?
2: Is it possible to let the Selenium server trying to restart multiple times, when the port is in use?
3: Is it possible to let the Selenium server start on a different port when the port is already in use?
4: Is it possible to stop Selenium server in a teardown process between single test suites manually?

Thanks.

**Comment by nevir** [comment]
Hmm, I wonder if certain ranges of ports are blocked within Codeship's build VMs...

> 1: Is it possible to use dynamic ports for every test suite?
> 2: Is it possible to let the Selenium server trying to restart multiple times, when the port is in use?
> 3: Is it possible to let the Selenium server start on a different port when the port is already in use?

WCT [attempts to find a free port](https://github.com/Polymer/web-component-tester/blob/master/runner/steps.js#L85) each time it starts up Selenium, so that _should_ be occurring. (I'm using [freeport](https://www.npmjs.com/package/freeport)).

Note that there's potential for a race due to how freeport operates, as it just creates a socket to find an open port, and then closes it - someone else could claim that port before selenium fully boots. Is WCT trying to reuse that same port, or do you have any logging that might indicate what else took that port?

(WCT's web server [also uses freeport](https://github.com/Polymer/web-component-tester/blob/master/runner/steps.js#L114))

4: Is it possible to stop Selenium server in a teardown process between single test suites manually?

That would be a lot of work and add considerable latency to your test suites; what're you trying to do w/ this behavior?

**Comment by nevir** [comment]
In the next release, you'll be able to specify a particular port for selenium to use (otherwise it'll resort to the `freeport` package). You'll also be able to skip the selenium step entirely if you would rather manage your own:

`wct.conf.js`:
```js
module.exports = {
  plugins: {
    local: {
      seleniumPort: 12345,
      skipSelenium: true, // You have your own selenium server running.
    }
  }
};
```
