### ISSUE TITLE
Integrate accessibility testing

### ISSUE THREAD

**Issue by azakus** [Polymer/web-component-tester#123]
The Chrome accessibility team maintains [GoogleChrome/accessibility-developer-tools](https://github.com/GoogleChrome/accessibility-developer-tools), which would make it nice and easy to test for accessibility of web components. On npm as `accessibility-developer-tools`.

I think the main work would be making mocha understand the output of the accessibility tests. It would still be up to the individual element author to make tests.

**Comment by azakus** [comment]
@cdata @alice

**Comment by alice** [comment]
https://code.google.com/p/chromium/codesearch#chromium/src/chrome/test/data/webui/test_api.js&q=runAccessibilityChecks&sq=package:chromium&l=1031&type=cs is the place where the audit is actually run in the Chrome webui test API.

https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/ui/webui/extensions/extension_settings_browsertest.js&q=runAccessibilityChecks&sq=package:chromium&l=28&type=cs shows an example of configuring the audit to ignore certain selectors for a given rule.

**Comment by nevir** [comment]
This lines up pretty nicely with #85 too

**Comment by ckortekaas** [comment]
+1 this would be an awesome addition!

We've been using https://github.com/yargalot/grunt-accessibility and https://github.com/globant-ui/arialinter, but I think they both had issues with shadow dom.

The google-accessibility-tester looks like it handles shadow dom / web components better than those two so we'll be looking forward to this integration with wct.

**Comment by addyosmani** [comment]
+1 for https://github.com/GoogleChrome/accessibility-developer-tools. I use it in my WIP accessibility audit CLI http://github.com/addyosmani/a11y and it tends to work well. 

I have however run into issues with how well it works with apps relying heavily on JS for rendered content, including Polymer and Ember. With a timeout, or a delay until some app-specified "ready" state has completed, I haven't been able to mimic the output you currently get from the accessibility DevTools extension. 

Unclear atm, if this is due to the age of Phantom or some other limitation. I could also be doing something silly :)

**Comment by azakus** [comment]
Added in 4da72e7de7ac6ffd037c218a9b63452a1fcbbe51
