### ISSUE TITLE
assert.isBelow not working

### ISSUE THREAD

**Issue by indolering** [Polymer/web-component-tester#160]
I'm getting an `assert.isBelow is not a function` when I try to run `assert.isBelow(average, 200, "Average search < 200ms");`

**Comment by nevir** [comment]
WCT currently bundles a somewhat old build of `chai` that lacks that :(

I've _just_ cleaned up the browser logic so that it depends on all of the testing libraries via bower. If you'd like to be a guinea pig, please try out `web-component-tester@3.0.0-rc1`, which'll pull the latest copies of chai and all the other libraries
