### ISSUE TITLE
All 1.x tests are failing

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/web-component-tester#466]
### Description
Currently all tests are failing both for our own elements and the Polymer 1.x elements e.g.
![image](https://cloud.githubusercontent.com/assets/7462342/21346796/ecfd8cfc-c673-11e6-8b9a-ebc9b7c810dc.png)

It seems that the problem started after https://github.com/Polymer/web-component-tester/commit/10e50669bd94c4ce1488d969004fa23d69abfa04

### Expected outcome

Tests should work as before.

### Actual outcome

All tests are failing.

### Steps to reproduce

execute e.g. /iron-input/test/index.html

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by IntranetFactory** [comment]
@e111077 is it intentional that your commit broke all existing tests? Or is that just a problem we face?

**Comment by web-padawan** [comment]
@IntranetFactory Actually `6.0.0` is not released yet. In order to upgrade, please read [this guide]https://github.com/PolymerElements/test-fixture#even-simpler-usage-in-mocha()

**Comment by IntranetFactory** [comment]
Breaking all our tests is not what I'd call "Even simpler usage".

And https://github.com/PolymerElements/test-fixture#even-simpler-usage-in-mocha unfortunately does not even explain how to fix the dozens of existing tests.

Isn't it possible to avoid breaking all tests?

**Comment by justinfagnani** [comment]
@IntranetFactory Sorry for the pain here.

We're trying to solve a problem where WCT can only depend on one version of `test-fixture`, but there will be two versions that projects might need: One that works with Polymer 1.x and Custom Elements v0, and one that works with Polymer 2.0 and Custom Elements v1. If we simply upgraded `test-fixture` we also would have broken all tests that implicitly depended on `text-fixture` 1.x

There are two solutions here on your end:

  1. Don't upgrade WCT to 6.0. Your tests actually depend on WCT 5.0 to pass, so they should be explicit about that. I'd reccommend running `npm i web-component-tester@^5.0.0 --save-dev` to fix WCT to a specific version in your projects.
  2. Install a specific version of `test-fixture` by running `bower i PolymerElement/test-fixture --save-dev`

There may be some way that we can try to determine which version of `test-fixture` you need by inspecting other dependencies, and bundle them both, but this would be a lot of complexity and probably break again if there's another version of `test-fixture` in the future.

**Comment by IntranetFactory** [comment]
It's not only our tests which are broken - but it seems that all test for Paper 1.x elements are broken as well. Will all tests for all existing 1.x elements be also fixed accordingly? 

Wouldn't make more sense to avoid such a breaking change by naming the "new" test-fixture e.g. test-fixture-mocha to make it clear that it is a different, incompatible element?

or to have it in a different branch, like the main Polymer/2.0-preview repo, to ensure that work for Polymer 2.0 doesn't break Polymer 1.x elements?

**Comment by justinfagnani** [comment]
We haven't released WCT 6 yet, so our element tests are still passing.

Our plan is to fix our element test configurations at a specific version of WCT (rather than just a `npm i web-component-tester` in .travis.yml) to be able to weather breaking changes in WCT, and we'll also have them install their test dependencies as dev dependencies.

We can't rename test-fixture, because it needs to retain its tag name and import path for references to work under both Polymer 1.x and Polymer 2.x tests. A different branch doesn't help, because eventually these will all be on master and they'll all be valid releases.

I did realize that test-fixture in the custom-elements-v1 branch does with with CEv0. Se we could possibly re-bundle it. The problem is that this bundling is exactly what we want to get away from because it fixes the dependency to the version of WCT, not the version of the project under test. WCT and everything it bundles is prevented from ever making breaking changes if a project implicitly depends on _any_ version of WCT.

So, we _might_ reverse the un-bundling decision here, but in general we want to unbundle and have projects specify their dev dependencies explicitly.

**Comment by IntranetFactory** [comment]
> but in general we want to unbundle and have projects specify their dev dependencies explicitly.
That's probably a good idea for the future. But I think that should be documented, recommended and announced, with enough lead time allowing element developers to prepare for that change e.g. coming with WCT 7+

paper-input seems to have an explicit dev-dependency on a fixed version - https://github.com/PolymerElements/paper-input/blob/master/bower.json#L48, but nevertheless the tests fail when executed in my current project.

So does this mean that I cannot mix elements depending on different WCT versions in one project? Will testing only work when all elements depend on the same WCT version? 

So will in the future any 3rd party element requesting WCT 6.0 then break again the tests of our elements when they still depend on WCT 4 or 5 ?

**Comment by justinfagnani** [comment]
Thanks for the link to paper-input, I'll check that out.

The way dependencies work, packages depend on WCT, not elements. So if you have multiple elements in one package, they all should work with the same version of WCT (given a normal project setup). WCT only tests elements in the local package, and not its dependencies, so you can mix and match dependending on elements with no tests, WCT 4, WCT 6, or some other test framework. #rd party packages have no effect on your test setup.

**Comment by justinfagnani** [comment]
paper-input tests are passing for me with wct 6. Did you run `npm i`?

**Comment by IntranetFactory** [comment]
>So if you have multiple elements in one package, they all should work with the same version of WCT
We have one "package" which depends mostly on our own elements, but also on 3rd party elements like some Polymer elements. We are in control of our elements - so we can control which WCT version we use. But we cannot control which WCT version 3rd parties use. We try to execute the tests of all elements in our package when we package our application. These tests suddenly fail. 

Does your feedback mean that we cannot continue to test 3rd party elements if they use another version of WCT?

We executed `bower update` and recognized that both our tests and the tests for Polymer elements suddenly failed.  We did not run `npm i` - should we?

**Comment by IntranetFactory** [comment]
and when I look at https://github.com/PolymerElements/paper-input I don't see any reference of `test-fixture-mocha.js`. From my understanding that file needs to be included for WCT 6.0. 

So did I just miss where the file is loaded in the paper-input tests or is my assumption that `test-fixture-mocha.js` will fix the errors I see wrong?

**Comment by IntranetFactory** [comment]
I need to add 

```
<link rel="import" href="../../test-fixture/test-fixture.html">
  <script src="../../test-fixture/test-fixture-mocha.js"></script>
```

to paper-input/test/paper-input.html to make the tests in this file to pass. I don't see these lines in the paper-input#master repo. So I'm wondering why/how paper-input/test/paper-input.html will work for you, but fail for me...

**Comment by justinfagnani** [comment]
When running 3rd party packages tests you'll need to actually install those packages dev dependencies and run tests how they need to be run for that package.

In the case of paper-* elements, they might have _coincidentally_ worked because you already installed their dev dependencies in your client, but there's no guarantee that this would work, and in general it won't. If a dependency decided to use Protractor instead of WCT, that would be its prerogative. If a dependency fixes it's version of WCT at 4.0, that's also its prerogative.

Because paper-input fixes it's version of WCT's bower package at ^4.0.0, it installs a version that bundles test-fixture, and the tests pass. I ran:

```
git clone https://github.com/PolymerElements/paper-input.git
cd paper-input/
bower i
polymer test -l chrome
```

This is the only way paper-input officially supports its tests

What we're saying is the current plan forward is to also have paper-input fix its version of WCTs npm package, so it gets known serving behavior too.

**Comment by IntranetFactory** [comment]
So far we had been able to execute the tests for all dependency elements in our package folder. I wasn't aware that this only _coincidentally_ worked stable for months across our elements and the Polymer elements.

From my understanding WCT was part of the platform - like polymer.html, providing a common convention across all elements. 

For me it seems like a step in the wrong direction when there is no common convention how elements should be tested and especially if elements can only be tested in isolation and not when being part of a package?

**Comment by justinfagnani** [comment]
There was never any intent on any of our projects to make them testable outside of a local installation via `git clone` and `bower install`. Without that workflow, they are not guaranteed to pull in their dev dependencies, dev dependencies would have to all be placed under regular dependencies.

Testing this way just isn't the norm with any package management ecosystem that I know of. You just shouldn't have to run our tests, we do that during development and on our CI servers.

**Comment by IntranetFactory** [comment]
> This is the only way paper-input officially supports its tests

https://www.polymer-project.org/1.0/docs/tools/tests lists another way to run tests: _Run tests interactively_

That's the way we currently work: install/update all dependencies needed and then _Run tests interactively_ from each components folder (e.g. `localhost:8080/components/my-el/test/my-el_test.html`)

So is _Run tests interactively_ not supported any longer?

**Comment by justinfagnani** [comment]
That's for the project you're working on. If you navigate to the tests for a dependency, they might fail due to not having their dev dependencies installed.

**Comment by IntranetFactory** [comment]
> If you navigate to the tests for a dependency, they might fail due to not having their dev dependencies installed.

In the past that was no problem and it *always* worked.

> they might fail due to not having their dev dependencies installed.
We always install all elements with their dev dependencies. So they can't be missing.

So how should I ensure that a certain combination of elements and dependencies work when I'm not able to run the tests for all elements?

> You just shouldn't have to run our tests, we do that during development and on our CI servers.
Unfortunately we needed to apply some patches to Polymer itself. So we need to always test all elements we use.

**Comment by justinfagnani** [comment]
> In the past that was no problem and it always worked.

Again, it only worked coincidentally. I'm actually surprised that we don't have tests listed under `ignore` in `bower.json`, since you typically _don't_ want to install tests of dependencies, since there's no way to ensure they could be run.

> We always install all elements with their dev dependencies. So they can't be missing.

How are you doing this? `bower i` doesn't install transitive dev dependencies, and there's no flag I'm aware of to force it to. If you already have a process where you can checkout each dependency individually, then things will be fine for our elements: we'll upgrade them to explicitly depend on a version of WCT and `polymer test` will defer to that. Like I showed with `paper-button` - its tests pass when invoked from WCT 6, because it explicitly depends on WCT 4.

> So how should I ensure that a certain combination of elements and dependencies work when I'm not able to run the tests for all elements?

Hopefully your own unit tests and integration tests take care of testing the interactions you depend on. Our packages with dependencies also test against certain combinations of versions.

Also, because we try to standardize on a single version of WCT and update all of our repos if necessary, we have a tool called Tattoo that independently checks out, installs, and runs WCT tests for an entire set of packages. Tatoo does the right thing for ensuring dev dependencies are installed: it checks out each package individually and runs `bower i` in each.

> Unfortunately we needed to apply some patches to some Polymer elements. So we need to always test all elements we use.

It'd be great if you could upstream these changes. If you can't I'd recommend a fork so that you can setup a CI server and run tests when you merge in changes from upstream.

I'm not sure what else to say other than what I've said already. The way common package managers are designed does not typically support checking out transitive dev dependencies and running their tests. Each package can have its own way of running tests, its own test dependencies, its own test build requirements. I don't think you'll find any packages in the npm or bower ecosystems that purposefully support this pattern.

**Comment by IntranetFactory** [comment]
Just one final question

Let's say I have an element a-b depending on x-y version 1

Another elenent c-d depends on x-y version 2

both a-b and c-d provided tests succeed

now my element depends on a-b and c-d and 

Currently I can just run tests of both to see if x-y v2 will break any tests

should I recreate all test of a-b and c-d in my element? 

now bring in 100+ elements depending on different version of dependencies, how will I be able to test the combination of them? not having versioned dependencies in the browser but being only able to test versioned dependencies seems like a major issue in interoparibilty in the future

**Comment by IntranetFactory** [comment]
In the current wct version *Run tests interactively* works again.
