### ISSUE TITLE
Using --compile flag doesn't transpile imports

### ISSUE THREAD

**Issue by tpluscode** [Polymer/web-component-tester#612]
I have test code written in ES6, which I `<script>` in a HTML test suite.
I run `wct --compile always`. In Chrome I get an error saying `Unexpected token import` and indeed I see the classes get compiled but module imports are left intact. 

Any way to make them work?

**Comment by usergenic** [comment]
This might have been addressed by the latest wct 6.2.0 release which includes updated version of polyserve with module compilation.  Should be rolling out new version of polymer-cli shortly which includes updated version of wct/polyserve if you are running tests with `polymer test` -- otherwise if you use `wct` at command line you can update now.

**Comment by usergenic** [comment]
@tpluscode if your `<script>` tag contains code with `import` you need to `<script type=module>` it.

**Comment by usergenic** [comment]
Closing issue.  Please re-open if you encounter issues after upgrading to wct 6.2.0 and using `<script type=module>`
