### ISSUE TITLE
Make SELENIUM_OVERRIDES available to override from base package.json

### ISSUE THREAD

**Issue by philippw** [Polymer/web-component-tester#675]
I'm trying to convince `wct-local` to download selenium and its drivers via an internal Artifactory server instead of directly from GitHub. `selenium-standalone` supports this via its `baseURL` settings.

However, as `selenium-standalone` is a transitive dependency of `wct-local` I cannot override the default values.
Fortunately, there's the `scripts/postinstall.js` and its `SELENIUM_OVERRIDES, which would allow for excatly that, would it not be the case that it only ever parses settings from `wct-local`'s own `package.json`.

Can we change the lookup path from `../package.json` to `../../../package.json` to be able to override the Selenium settings from the base package.json?

**Comment by nicojs** [comment]
I think using an environment variable for this is more common for these types of features. Also, this issue is reported to the wrong git repository. I think it should be reported to [wct-local](https://github.com/Polymer/wct-local/issues)

See this file: https://github.com/Polymer/wct-local/blob/master/scripts/postinstall.js

**Comment by philippw** [comment]
Moved to the correct issues tracker. Closing this bug now.
